import type {
  CandidateRisk,
  CandidateStrategy,
  CandidateSummary,
  EvidenceDatum,
  EvidenceStatus,
  QueueFilter,
  TopQueueSnapshot,
} from "@seekandscore/contracts";

interface CandidateSeed {
  name: string;
  locality: string;
  county: string;
  parcelId: string;
  acreage: number;
  strategy: CandidateStrategy;
  score: number;
  confidence: number;
  low: number;
  high: number;
  basis: number;
  previousRank: number | null;
  queueState: CandidateSummary["queueState"];
  thesis: string;
  nextAction: string;
  change?: string;
  evidenceStatus?: EvidenceStatus;
  riskLabel: string;
  riskDetail: string;
}

const seeds: CandidateSeed[] = [
  {
    name: "McAngus Road assemblage",
    locality: "Del Valle, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-01842",
    acreage: 6.4,
    strategy: "Airport parking",
    score: 91.8,
    confidence: 0.82,
    low: 980000,
    high: 1260000,
    basis: 795000,
    previousRank: 3,
    queueState: "ready",
    thesis: "Large usable footprint near the airport corridor with a conservative land basis and more than one plausible current-use exit.",
    nextAction: "Verify TxDOT access history and request a preliminary circulation review.",
    change: "Access observation verified from a newer county record.",
    riskLabel: "Access permit not confirmed",
    riskDetail: "Road frontage is mapped; driveway approval remains an underwriting dependency.",
  },
  {
    name: "FM 969 frontage tract",
    locality: "Webberville, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-02117",
    acreage: 12.8,
    strategy: "Opportunity Zone",
    score: 90.6,
    confidence: 0.78,
    low: 1120000,
    high: 1450000,
    basis: 910000,
    previousRank: 1,
    queueState: "research",
    thesis: "Employment-corridor frontage and an effective tract designation support deeper development research without changing base value.",
    nextAction: "Confirm utility capacity and model substantial-improvement scenarios separately.",
    riskLabel: "Utility capacity unknown",
    riskDetail: "Service area is known, but a current capacity letter is not available.",
  },
  {
    name: "Lockhart industrial edge",
    locality: "Lockhart, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-00491",
    acreage: 8.1,
    strategy: "Land banking",
    score: 89.9,
    confidence: 0.86,
    low: 640000,
    high: 810000,
    basis: 515000,
    previousRank: 5,
    queueState: "watching",
    thesis: "A low-basis edge parcel with highway access signals and several conservative hold or resale paths.",
    nextAction: "Compare the zoning map against the latest comprehensive-plan amendment.",
    change: "Rank rose after a nearby infrastructure award was recorded.",
    riskLabel: "Entitlement is preliminary",
    riskDetail: "Future-use mapping is not permission for an industrial use today.",
  },
  {
    name: "Old Bastrop Highway infill",
    locality: "Austin, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-02908",
    acreage: 3.2,
    strategy: "Airport parking",
    score: 88.7,
    confidence: 0.69,
    low: 890000,
    high: 1170000,
    basis: 740000,
    previousRank: null,
    queueState: "new",
    thesis: "A newly resolved tract inside the airport search corridor with favorable geometry and strong frontage exposure.",
    nextAction: "Resolve the conflicting acreage observations before capacity modeling.",
    change: "New candidate after parcel identity resolution.",
    evidenceStatus: "conflicting",
    riskLabel: "Acreage conflict",
    riskDetail: "Assessor and recorded-plat observations differ by 0.18 acres.",
  },
  {
    name: "Cedar Creek homestead acreage",
    locality: "Cedar Creek, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-01033",
    acreage: 14.6,
    strategy: "Lifestyle",
    score: 87.4,
    confidence: 0.84,
    low: 720000,
    high: 940000,
    basis: 595000,
    previousRank: 4,
    queueState: "ready",
    thesis: "Tree cover, usable terrain, and Austin proximity create lifestyle demand while the basis remains supportable as land.",
    nextAction: "Order a desktop wetlands screen and verify recorded access.",
    riskLabel: "Wetlands screen pending",
    riskDetail: "A mapped drainage feature crosses the southeast corner of the tract.",
  },
  {
    name: "SH 71 service-road parcel",
    locality: "Bastrop, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-01604",
    acreage: 4.9,
    strategy: "Land banking",
    score: 86.9,
    confidence: 0.75,
    low: 810000,
    high: 1060000,
    basis: 670000,
    previousRank: 8,
    queueState: "research",
    thesis: "Service-road visibility and multiple commercial-adjacent uses make the parcel worth disciplined access and entitlement review.",
    nextAction: "Verify legal access and active development applications nearby.",
    change: "Moved two positions on updated comparable evidence.",
    riskLabel: "Frontage is not access",
    riskDetail: "Mapped frontage must not be treated as a permitted curb cut.",
  },
  {
    name: "Q2 east overflow site",
    locality: "Austin, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-03176",
    acreage: 2.7,
    strategy: "Event parking",
    score: 86.1,
    confidence: 0.73,
    low: 1540000,
    high: 1920000,
    basis: 1380000,
    previousRank: 6,
    queueState: "watching",
    thesis: "An under-improved parcel near a high-demand event node has interim-use potential and longer-term redevelopment optionality.",
    nextAction: "Separate current permitted use from the event-parking scenario.",
    riskLabel: "Current use unverified",
    riskDetail: "Parking revenue remains a scenario until use and operating requirements are confirmed.",
  },
  {
    name: "Mustang Ridge corner tract",
    locality: "Mustang Ridge, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-00722",
    acreage: 9.3,
    strategy: "Buildable land",
    score: 85.6,
    confidence: 0.88,
    low: 580000,
    high: 735000,
    basis: 470000,
    previousRank: 9,
    queueState: "ready",
    thesis: "Buildable topography and regional access create a practical land thesis with manageable known hazards.",
    nextAction: "Confirm water provider boundary and obtain a septic feasibility opinion.",
    riskLabel: "Water source unresolved",
    riskDetail: "Two provider boundaries appear close to the parcel; neither is verified as serving it.",
  },
  {
    name: "Elroy Road long-hold parcel",
    locality: "Elroy, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-02550",
    acreage: 5.8,
    strategy: "Distress",
    score: 84.8,
    confidence: 0.67,
    low: 760000,
    high: 1010000,
    basis: 620000,
    previousRank: null,
    queueState: "new",
    thesis: "A supported long-hold and under-improvement pattern warrants research, but no personal circumstance is inferred.",
    nextAction: "Review ownership history and confirm the current record-owner entity.",
    change: "New candidate from a deed-history observation.",
    evidenceStatus: "stale",
    riskLabel: "Ownership freshness",
    riskDetail: "The latest normalized ownership observation is older than the target freshness window.",
  },
  {
    name: "Colorado River terrace",
    locality: "Bastrop, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-01881",
    acreage: 18.2,
    strategy: "Lifestyle",
    score: 84.2,
    confidence: 0.8,
    low: 970000,
    high: 1240000,
    basis: 815000,
    previousRank: 7,
    queueState: "research",
    thesis: "River-area amenity and privacy produce a strong lifestyle signal, tempered by explicit flood and access diligence.",
    nextAction: "Map usable high ground and review the latest flood-elevation evidence.",
    riskLabel: "Flood exposure",
    riskDetail: "A meaningful portion intersects a mapped hazard area; usable acreage is not yet verified.",
  },
  {
    name: "FM 812 employment tract",
    locality: "Pilot Knob, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-03406",
    acreage: 7.7,
    strategy: "Opportunity Zone",
    score: 83.7,
    confidence: 0.77,
    low: 1180000,
    high: 1510000,
    basis: 1030000,
    previousRank: 13,
    queueState: "watching",
    thesis: "The parcel combines employment growth signals with an effective tract designation and a credible current-use fallback.",
    nextAction: "Validate designation vintage and test a no-tax-benefit base case.",
    change: "Designation vintage was verified.",
    riskLabel: "Tax eligibility is separate",
    riskDetail: "Parcel location does not establish project, fund, business, or taxpayer qualification.",
  },
  {
    name: "Dale four-corners acreage",
    locality: "Dale, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-00863",
    acreage: 22.4,
    strategy: "Buildable land",
    score: 82.9,
    confidence: 0.83,
    low: 520000,
    high: 690000,
    basis: 425000,
    previousRank: 14,
    queueState: "ready",
    thesis: "Low land basis, usable geometry, and multiple homesite scenarios offset a longer hold and utility uncertainty.",
    nextAction: "Verify easement width and obtain utility-extension ranges.",
    change: "Two-position gain after shape metrics completed.",
    riskLabel: "Utility extension cost",
    riskDetail: "Mapped lines are nearby, but extension cost and capacity are unknown.",
  },
  {
    name: "Domain service commercial pad",
    locality: "Austin, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-03813",
    acreage: 1.9,
    strategy: "Event parking",
    score: 82.3,
    confidence: 0.72,
    low: 1760000,
    high: 2250000,
    basis: 1620000,
    previousRank: 12,
    queueState: "research",
    thesis: "Small-format infill close to major activity centers supports a staged interim-use and redevelopment investigation.",
    nextAction: "Reconcile zoning records and estimate a conservative hold cost.",
    evidenceStatus: "conflicting",
    riskLabel: "Zoning conflict",
    riskDetail: "Two official map services return different classifications for the same geometry.",
  },
  {
    name: "Bergstrom south acreage",
    locality: "Del Valle, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-04002",
    acreage: 10.5,
    strategy: "Airport parking",
    score: 81.8,
    confidence: 0.74,
    low: 1280000,
    high: 1670000,
    basis: 1090000,
    previousRank: 11,
    queueState: "watching",
    thesis: "Scale and corridor proximity support a land-bank thesis while airport parking remains a preliminary scenario only.",
    nextAction: "Screen drainage constraints before estimating potential spaces.",
    riskLabel: "Drainage design unknown",
    riskDetail: "Gross acreage cannot be converted to parking capacity without civil review.",
  },
  {
    name: "Smithville west pasture",
    locality: "Smithville, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-02298",
    acreage: 31.7,
    strategy: "Land banking",
    score: 81.1,
    confidence: 0.85,
    low: 690000,
    high: 880000,
    basis: 565000,
    previousRank: 16,
    queueState: "ready",
    thesis: "A conservative per-acre basis and clean parcel identity support a long-duration hold with multiple rural exits.",
    nextAction: "Check mineral reservations and validate agricultural carrying costs.",
    riskLabel: "Mineral rights unknown",
    riskDetail: "The current deed extract does not resolve mineral reservations.",
  },
  {
    name: "Lytton Springs tax file",
    locality: "Lytton Springs, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-01041",
    acreage: 6.1,
    strategy: "Distress",
    score: 80.5,
    confidence: 0.64,
    low: 410000,
    high: 545000,
    basis: 325000,
    previousRank: 18,
    queueState: "research",
    thesis: "Supported public-record signals justify title and tax research, not assumptions about the owner or likely acquisition cost.",
    nextAction: "Reconcile delinquency balance and title-party observations.",
    change: "Public tax record changed materially.",
    evidenceStatus: "estimated",
    riskLabel: "Acquisition cost uncertain",
    riskDetail: "Minimum or reported balances are not the expected all-in acquisition cost.",
  },
  {
    name: "Bluebonnet Trail parcel",
    locality: "Manor, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-04327",
    acreage: 4.4,
    strategy: "Buildable land",
    score: 79.8,
    confidence: 0.7,
    low: 610000,
    high: 790000,
    basis: 530000,
    previousRank: null,
    queueState: "new",
    thesis: "A newly assembled evidence set suggests practical homesite potential near established growth corridors.",
    nextAction: "Confirm legal lot status and resolve the access easement.",
    change: "New after two source parcels were linked.",
    riskLabel: "Legal lot status unknown",
    riskDetail: "Parcel identity is resolved; subdivision compliance is not.",
  },
  {
    name: "Rosanky wooded tract",
    locality: "Rosanky, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-02661",
    acreage: 19.1,
    strategy: "Lifestyle",
    score: 79.2,
    confidence: 0.81,
    low: 560000,
    high: 735000,
    basis: 485000,
    previousRank: 19,
    queueState: "watching",
    thesis: "Wooded privacy and shape quality create a credible lifestyle parcel with acceptable distance from employment centers.",
    nextAction: "Review wildfire exposure and verify an all-weather access route.",
    riskLabel: "Wildfire exposure",
    riskDetail: "Vegetation and response-time observations warrant a site-level review.",
  },
  {
    name: "US 183 south reserve",
    locality: "Lockhart, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-01202",
    acreage: 15.8,
    strategy: "Land banking",
    score: 78.6,
    confidence: 0.76,
    low: 850000,
    high: 1110000,
    basis: 735000,
    previousRank: 17,
    queueState: "research",
    thesis: "Regional connectivity and a moderate basis justify monitoring, with current economics carrying the thesis.",
    nextAction: "Verify frontage constraints and update sales-comparable distance bands.",
    riskLabel: "Comparable coverage thin",
    riskDetail: "Texas non-disclosure limits direct sale-price evidence for the immediate area.",
  },
  {
    name: "Onion Creek edge tract",
    locality: "Austin, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-04519",
    acreage: 7.2,
    strategy: "Opportunity Zone",
    score: 78.0,
    confidence: 0.62,
    low: 960000,
    high: 1320000,
    basis: 845000,
    previousRank: 22,
    queueState: "research",
    thesis: "A designated tract and employment access make this research-worthy, but flood and buildable-area evidence control the decision.",
    nextAction: "Calculate usable acreage from current flood and drainage layers.",
    change: "Moved after designation geometry was refreshed.",
    riskLabel: "Usable area unresolved",
    riskDetail: "Gross acreage materially overstates likely developable acreage.",
  },
  {
    name: "Paige rail-adjacent parcel",
    locality: "Paige, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-02907",
    acreage: 11.3,
    strategy: "Land banking",
    score: 77.5,
    confidence: 0.79,
    low: 430000,
    high: 575000,
    basis: 365000,
    previousRank: 20,
    queueState: "watching",
    thesis: "A patient land basis and regional logistics signal provide optionality if access and noise impacts remain manageable.",
    nextAction: "Verify crossing access and quantify the rail adjacency discount.",
    riskLabel: "Rail adjacency",
    riskDetail: "Noise, vibration, and crossing constraints may reduce residential liquidity.",
  },
  {
    name: "Kyle ETJ acreage",
    locality: "Uhland, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-01477",
    acreage: 13.6,
    strategy: "Buildable land",
    score: 76.8,
    confidence: 0.71,
    low: 780000,
    high: 990000,
    basis: 680000,
    previousRank: 24,
    queueState: "research",
    thesis: "Growth proximity and tract size support a buildable-land review while jurisdictional boundaries remain explicit unknowns.",
    nextAction: "Resolve ETJ status and subdivision rules as of the ranking date.",
    change: "Two-position gain on updated jurisdiction evidence.",
    riskLabel: "Jurisdiction boundary",
    riskDetail: "The candidate sits close to a changing ETJ boundary and needs dated verification.",
  },
  {
    name: "Pearce Lane remnant",
    locality: "Del Valle, TX",
    county: "Travis",
    parcelId: "TX-453-SYN-04731",
    acreage: 2.3,
    strategy: "Airport parking",
    score: 76.2,
    confidence: 0.68,
    low: 670000,
    high: 875000,
    basis: 590000,
    previousRank: 21,
    queueState: "watching",
    thesis: "The location is compelling, but constrained scale means access and usable-area evidence must be unusually strong.",
    nextAction: "Run a geometry-only capacity range before further research spend.",
    evidenceStatus: "estimated",
    riskLabel: "Small usable footprint",
    riskDetail: "Setbacks and circulation may make the gross acreage economically misleading.",
  },
  {
    name: "Buda east hold parcel",
    locality: "Buda, TX",
    county: "Caldwell",
    parcelId: "TX-055-SYN-01635",
    acreage: 10.9,
    strategy: "Land banking",
    score: 75.7,
    confidence: 0.8,
    low: 760000,
    high: 950000,
    basis: 665000,
    previousRank: 25,
    queueState: "ready",
    thesis: "A conservative hold with good geometry and multiple rural-use exits earns a place near the bottom of the active queue.",
    nextAction: "Validate agricultural exemption continuity and annual carrying cost.",
    riskLabel: "Holding-cost sensitivity",
    riskDetail: "Loss of the current tax treatment would materially change the carry scenario.",
  },
  {
    name: "Taylor Lane estate tract",
    locality: "Elgin, TX",
    county: "Bastrop",
    parcelId: "TX-021-SYN-03140",
    acreage: 16.5,
    strategy: "Distress",
    score: 75.1,
    confidence: 0.61,
    low: 590000,
    high: 790000,
    basis: 495000,
    previousRank: 23,
    queueState: "research",
    thesis: "A source-supported ownership transition warrants careful record research without inferring motivation or decision authority.",
    nextAction: "Resolve current title parties and authority scope before any contact research.",
    evidenceStatus: "unknown",
    riskLabel: "Authority unresolved",
    riskDetail: "No person or entity is yet verified as authorized to discuss the property.",
  },
];

function makeEvidence(seed: CandidateSeed, index: number): EvidenceDatum[] {
  const primaryStatus = seed.evidenceStatus ?? "verified";

  return [
    {
      id: `${seed.parcelId}-identity`,
      label: "Parcel identity",
      value: seed.parcelId,
      status: primaryStatus === "conflicting" ? "conflicting" : "verified",
      source: `${seed.county} County parcel records`,
      observedAt: "2026-08-11T15:20:00-05:00",
      detail: "Synthetic source observation for interface validation.",
    },
    {
      id: `${seed.parcelId}-value`,
      label: "Value range",
      value: `${formatMoneyCompact(seed.low)}–${formatMoneyCompact(seed.high)}`,
      status: "estimated",
      source: `Comparable set CTX-${String(index + 1).padStart(3, "0")}`,
      observedAt: "2026-08-10T09:00:00-05:00",
      detail: "Scenario estimate; not an appraisal or offer recommendation.",
    },
    {
      id: `${seed.parcelId}-owner`,
      label: "Ownership role",
      value: primaryStatus === "unknown" ? "Unresolved" : "Record owner observed",
      status: primaryStatus === "stale" || primaryStatus === "unknown" ? primaryStatus : "verified",
      source: "Recorded deed and assessor observations",
      observedAt: primaryStatus === "stale" ? "2025-10-04T12:00:00-05:00" : "2026-08-09T12:00:00-05:00",
      detail: "A record-owner observation is not contact-point or negotiation authority.",
    },
    {
      id: `${seed.parcelId}-geo`,
      label: "Risk overlays",
      value: index % 3 === 0 ? "Review required" : "Screen complete",
      status: index % 3 === 0 ? "estimated" : "verified",
      source: "Versioned public GIS layers",
      observedAt: "2026-08-08T18:30:00-05:00",
      detail: "Desktop screening requires site and professional verification.",
    },
  ];
}

function makeRisks(seed: CandidateSeed, index: number): CandidateRisk[] {
  return [
    {
      id: `${seed.parcelId}-risk-primary`,
      label: seed.riskLabel,
      detail: seed.riskDetail,
      severity: index % 5 === 3 ? "critical" : "elevated",
    },
    {
      id: `${seed.parcelId}-risk-title`,
      label: "Title review not complete",
      detail: "No title, survey, legal, or environmental conclusion is represented.",
      severity: "watch",
    },
    {
      id: `${seed.parcelId}-risk-source`,
      label: index % 4 === 0 ? "Source freshness watch" : "Field verification pending",
      detail: "The ranking remains subject to due diligence and source refreshes.",
      severity: "watch",
    },
  ];
}

function makeCandidate(seed: CandidateSeed, index: number): CandidateSummary {
  const evidence = makeEvidence(seed, index);
  const identityReady = !evidence.some((item) =>
    ["unknown", "conflicting", "stale"].includes(item.status),
  );

  return {
    id: `candidate-${String(index + 1).padStart(2, "0")}`,
    rank: index + 1,
    previousRank: seed.previousRank,
    name: seed.name,
    locality: seed.locality,
    county: seed.county,
    parcelId: seed.parcelId,
    acreage: seed.acreage,
    strategy: seed.strategy,
    queueState: seed.queueState,
    overallScore: seed.score,
    confidence: seed.confidence,
    valueRange: { low: seed.low, high: seed.high },
    likelyBasis: seed.basis,
    thesis: seed.thesis,
    nextAction: seed.nextAction,
    newSinceLastReview: seed.previousRank === null,
    materialChange: seed.change ?? null,
    risks: makeRisks(seed, index),
    evidence,
    outreachGate: {
      status: "blocked",
      reviewedChecks: identityReady ? 2 : 1,
      totalChecks: 5,
      blockers: [
        ...(identityReady ? [] : ["Responsible-party identity needs review"]),
        "No approved contact-point source",
        "Texas acquisition policy is not activated",
        "All outbound channels are disabled",
      ],
    },
  };
}

export const topQueueSnapshot: TopQueueSnapshot = {
  id: "ctx-top25-2026-08-12",
  label: "Top 25",
  region: "Central Texas",
  timeZone: "America/Chicago",
  asOf: "2026-08-12T07:30:00-05:00",
  modelVersion: "central-texas-v1 · draft",
  isSynthetic: true,
  candidates: seeds.map(makeCandidate),
};

export function formatMoneyCompact(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    notation: "compact",
    maximumFractionDigits: value >= 1_000_000 ? 2 : 0,
  }).format(value);
}

export function rankMovement(candidate: Pick<CandidateSummary, "rank" | "previousRank">): number | null {
  if (candidate.previousRank === null) return null;
  return candidate.previousRank - candidate.rank;
}

export function filterCandidates(
  candidates: CandidateSummary[],
  filter: QueueFilter,
  search: string,
): CandidateSummary[] {
  const query = search.trim().toLocaleLowerCase();

  return candidates.filter((candidate) => {
    const filterMatches =
      filter === "all" ||
      (filter === "new" && candidate.newSinceLastReview) ||
      (filter === "moved" && (rankMovement(candidate) ?? 0) !== 0) ||
      (filter === "needs_review" && candidate.queueState === "research");

    if (!filterMatches) return false;
    if (!query) return true;

    return [
      candidate.name,
      candidate.locality,
      candidate.county,
      candidate.parcelId,
      candidate.strategy,
    ].some((value) => value.toLocaleLowerCase().includes(query));
  });
}
